version: "3.9"
services:
  app:
    build: ./infra/php
    ports:
      - 5173:5173
    volumes:
      - ./src:/data
  web:
    image: nginx:alpine3.18
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/log/mysql
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1 
      - PMA_HOSTS=db
      - PMA_USER=user
      - PMA_PASSWORD=secret
    ports:
      - "3001:80"

volumes:
  db-store:
